In [53]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [54]:
iris_df = pd.read_csv("Iris.csv")
iris_df.head()
iris_df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [55]:
iris_df =iris_df.replace({"Species":  {"Iris-setosa":1,"Iris-versicolor":2, "Iris-virginica":3}})

In [56]:
X = iris_df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].values
y= iris_df[['Species']].values

In [57]:
#X[0:5]
y[0:5]

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [58]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (120, 4) (120, 1)
Test set: (30, 4) (30, 1)


In [60]:
#Logistic Regression

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.01, solver='liblinear')

In [62]:
yhat = LR.predict(X_test)
yhat

array([3, 1, 3, 3, 3, 3, 3, 1, 1, 3, 1, 1, 1, 3, 3, 1, 2, 1, 1, 3, 1, 3,
       2, 1, 1, 1, 1, 1, 1, 3])

In [63]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.18542761, 0.36926791, 0.44530448],
       [0.49982913, 0.26739835, 0.23277253],
       [0.15136412, 0.37106058, 0.47757529],
       [0.13903275, 0.35667206, 0.50429519],
       [0.16100915, 0.36471482, 0.47427603],
       [0.26907872, 0.35751132, 0.37340996],
       [0.23185227, 0.3766608 , 0.39148693],
       [0.52728739, 0.2503734 , 0.22233921],
       [0.51286356, 0.25919423, 0.22794221],
       [0.23325831, 0.36898201, 0.39775968],
       [0.47205754, 0.32813605, 0.19980641],
       [0.50932828, 0.29598081, 0.19469091],
       [0.48870007, 0.32614869, 0.18515124],
       [0.26547406, 0.3587554 , 0.37577053],
       [0.20906549, 0.39110407, 0.39983044],
       [0.49055023, 0.31913268, 0.19031709],
       [0.29516506, 0.42485811, 0.27997683],
       [0.50456264, 0.3097345 , 0.18570286],
       [0.50257546, 0.2974838 , 0.19994074],
       [0.21420092, 0.37550613, 0.41029296],
       [0.4965721 , 0.31006349, 0.19336441],
       [0.20737039, 0.33019142, 0.46243818],
       [0.

In [64]:
#confusion matrix


# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, solver='lbfgs', multi_class='auto')
classifier.fit(X_train, y_train)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [65]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
# Predict probabilities
probs_y=classifier.predict_proba(X_test)
### Print results 
probs_y = np.round(probs_y, 2)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[16  0  0]
 [ 0  4  1]
 [ 0  1  8]]


In [66]:
from sklearn.metrics import accuracy_score
_pred = classifier.predict(X_test)
y_pred = classifier.predict(X_test)
print("Train data accuracy:",accuracy_score(y_true = y_train, y_pred=classifier.predict(X_train)))
print("Test data accuracy:",accuracy_score(y_true = y_test, y_pred=y_pred))

Train data accuracy: 0.9833333333333333
Test data accuracy: 0.9333333333333333
